### ISSUE TITLE
BUG: Package does not work with latest version of `aws-cdk-lib`

### ISSUE THREAD

**Issue by nguyen102** [udondan/cdk-ssm-document#29] opened 2022-04-13 04:45 UTC
When I try to run `cdk synth` or `cdk deploy`, I get the following error.
```
> "cdk synth"

/Users/tim/workplace/ma-mono/common/temp/node_modules/.pnpm/cdk-iam-floyd@0.300.0_ff8e2a29703a7cffac9ed3bbb4473395/node_modules/cdk-iam-floyd/lib/shared/policy-statement/6-principals.js:29
        this.principals = {};
                        ^

TypeError: Cannot set property principals of [object Object] which has only a getter
    at new PolicyStatementWithPrincipal (/Users/tim/workplace/ma-mono/common/temp/node_modules/.pnpm/cdk-iam-floyd@0.300.0_ff8e2a29703a7cffac9ed3bbb4473395/node_modules/cdk-iam-floyd/lib/shared/policy-statement/6-principals.js:29:25)
```

This is what my `package.json` looks like
```
 "dependencies": {
    "aws-cdk-lib": "^2.0.0",
    "constructs": "^10.0.0",
    "cdk-ssm-document": "^3.1.0",
    "cdk-iam-floyd": "^0.300.0",
  },
  ```
  
  This is what my code looks like
  ```
    private _createSMDocuments(): void {
    const cfnDoc = new Document(this._stack, 'SSMDoc', {
      name: `${this._stack.stackName}-SSMDoc`,
      documentType: 'Automation',
      content: fs
        .readFileSync(join(__dirname, `../../src/SSM.yaml`), 'utf8')
        .toString()
    });
  }
  ```
  
 If I set `aws-cdk-lib` to be explicitly `2.0.0`, I no longer get the error.

```
 "dependencies": {
    "aws-cdk-lib": "2.0.0",
    "constructs": "^10.0.0",
    "cdk-ssm-document": "^3.1.0",
    "cdk-iam-floyd": "^0.300.0",
  },
  ```

**Comment by udondan** [comment] 2022-04-13 08:07
Hi Tim,

the problem is related to iam-floyd. CDK 2.20.0 introduced a change that was conflicting with an internal floyd class property. This is fixed with [cdk-iam-floyd v0.351.0](https://github.com/udondan/iam-floyd/releases/tag/v0.351.0). You should be able it fix the issue by updating the version in your package.json.

I also have planned to remove the dependency to floyd - but not sure when I will find the time to do so.

Cheers,
Daniel

**Comment by nguyen102** [comment] 2022-04-13 14:09
Thank you! This worked.

**Comment by nguyen102** [comment] 2022-04-14 02:52
@udondan I believe this fixes the issue. Can you take a look?
https://github.com/udondan/cdk-ssm-document/pull/30

**Comment by udondan** [comment] 2022-04-20 16:48
Sorry for the delay. I'm really not having much time currently.

3.1.1 has just been released which removes floyd.

**Closed by udondan** 2022-04-20 16:48 UTC

**Comment by nguyen102** [comment] 2022-04-20 17:21
Thank you so much Daniel!
